### PR TITLE
fixes issue #257 by letting yt-dlp handle the download

### PR DESCRIPTION
**Pull request by vinyesm**
Hi,

A suggestion to fix https://github.com/iejMac/video2dataset/issues/257 and to be able to download videos for any video platform supported by yt-dlp is to let yt-dlp handle the download and throw error if not supported. If error the url is then skipped (current behavior). Tested with dailymotion links.

### CODE REVIEW

**Comment by rom1504** [comment]
Thanks!

Can you fix the failing tests and also add a new one with a non YouTube video at https://github.com/vinyesm/video2dataset/blob/main/tests/test_downloaders.py ?

**Comment by rom1504** [comment]
Also can you add some info in the readme to inform users video2dataset supports all the platforms supported by yt-dlp?

**Comment by vinyesm** [comment]
Thank you! I added info in the readme and updated https://github.com/vinyesm/video2dataset/blob/main/tests/test_downloaders.py. 
The [lint error ](https://github.com/iejMac/video2dataset/actions/runs/6484040940/job/17610715547?pr=258) does not seem linked to the modified files

**Comment by rom1504** [comment]
looks good, fixing lint at #259

**Review by rom1504 — APPROVED** [review]

**Comment by rom1504** [comment]
Thanks!

**Pull request merged**
