### PR TITLE
Download worker refactor

### PR DESCRIPTION
**Pull request by MattUnderscoreZhang**
Unifies SubsetWorker and DownloadWorker logic.
The two classes can probably be combined at this point.

Merge after #287.

### CODE REVIEW

**Comment by rom1504** [comment]
Can you rebase please ?

**Comment by MattUnderscoreZhang** [comment]
Ok, done

**Comment by MattUnderscoreZhang** [comment]
To describe high-level what happened here, I took overlapping logic from subset_worker and download_worker, and moved them to a common file worker.py. I tried to fully combine the two into a single class, but was unable to do so right now due to differences in how they load input data.

The main reason I did this was because both workers use the video processing subsamplers, which I'm trying to rewrite to not use temp file read/writes. By putting the video processing logic in a single file, it's easier to work with.

**Comment by rom1504** [comment]
looks pretty good to me, let's merge

**Pull request merged**
