### PR TITLE
ClippingSubsampler: improve clip accuracy

### PR DESCRIPTION
**Pull request by iejMac**

### CODE REVIEW

**Comment by iejMac** [comment]
problem was with the first clip - I thought ss cuts the video but it just seeks to that timeframe which makes no difference for segment_times

**Comment by iejMac** [comment]
not sure what to do here... either I'm not seeing something or there's some weird difference of FFmpeg versions

**Comment by iejMac** [comment]
testing on cluster now then merging

**Comment by rom1504** [comment]
Can you enable to propose to update the branch in the repo setting?

**Comment by iejMac** [comment]
merging

**Pull request merged**
