### PR TITLE
Subset worker refactor

### PR DESCRIPTION
**Pull request by MattUnderscoreZhang**
Tested with my processing workflow (framerate resampling, resizing, cropping, cut finding, clipping).
Results are identical to before.

Merge after #275.

### CODE REVIEW

**Comment by rom1504** [comment]
I merged #275 ; can you rebase here ?

**Comment by MattUnderscoreZhang** [comment]
Ok done

**Comment by iejMac** [comment]
looks good on first glance

**Comment by MattUnderscoreZhang** [comment]
Can we merge the worker requests?

**Comment by rom1504** [comment]
What do you mean by "requests" ?

**Comment by rom1504** [comment]
Lgtm, this is not doing much, just moving the code around, a bit better

**Pull request merged**
