### PR TITLE
Added width and height options for ResolutionSubsampler

### PR DESCRIPTION
**Pull request by MattUnderscoreZhang**

### CODE REVIEW

**Comment by MattUnderscoreZhang** [comment]
Pushed commit to fix linting.

**Comment by iejMac** [comment]
@MattUnderscoreZhang if you can resolve the conflict and tests pass I'm fine with merging this. Thanks for all the contributions!

**Comment by MattUnderscoreZhang** [comment]
Awesome, it's done.

**Comment by iejMac** [comment]
nice job!

**Pull request merged**
