### PR TITLE
Add contribution guide.

### PR DESCRIPTION
**Pull request by rom1504**
Should help merging PR without introducing issues

### CODE REVIEW

**Comment by rom1504** [comment]
any thought @iejMac @MattUnderscoreZhang ?

**Comment by MattUnderscoreZhang** [comment]
It may also be good to specify what kind of environment to test on. For example, one with at least 16 cores. And it would be difficult for most people to test that e.g. Slurm is still working correctly.

**Comment by MattUnderscoreZhang** [comment]
Unfortunately it's hard to specify a general test, because sometimes you also want to check that whatever subsampler you touched didn't reduce the speed. The webvid config specified basically only does video download, but e.g. if you touch the resolution subsampler you'd want to test with a config that included resolution downscaling in its processing pipeline. Thus it may make sense to test with your specific use case, as I did. Doing so would make the 14.4 videos/s/core benchmark even less relevant.

**Comment by rom1504** [comment]
Yes we can add these details.

The correct way to address this is many automated tests, see #310 

But a manual test of that kind is better than nothing

**Comment by rom1504** [comment]
> The 14.4 videos/s/core probably depends on your system though

I bet it doesn't depend that much. It may vary .5-2x but not much more

**Comment by MattUnderscoreZhang** [comment]
Is it possible to set up a runner on an environment you guys have access to? You'd have to be ok with it running each time someone does a pull request, but it would make it easier to compare numbers on a standard setup.

**Pull request merged**
