### PR TITLE
logger: add bytes/s metric

### PR DESCRIPTION
**Pull request by iejMac**

### CODE REVIEW

**Comment by iejMac** [comment]
TODO:
- [ ] Aggregate with SpeedLogger
- [ ] Add video_seconds/s
- [ ] Maybe normalized versions by worker count
- [ ] Test out on some small run

**Comment by iejMac** [comment]
I think I need to edit this:https://github.com/iejMac/video2dataset/blob/4a23e01382578e7478aba2775c6c7ddf7212c1f6/video2dataset/logger.py#L196

**Comment by iejMac** [comment]
Screen Shot 2022-12-25 at 1 44 08 PM
Screen Shot 2022-12-25 at 1 44 23 PM

**Comment by rom1504** [comment]
Nice

**Comment by rom1504** [comment]
Nice

**Pull request merged**
