### PR TITLE
Fix for issue #263

### PR DESCRIPTION
**Pull request by MattUnderscoreZhang**

### CODE REVIEW

**Comment by iejMac** [comment]
@MattUnderscoreZhang nice, if you can get the tests to pass we can merge, thanks for this.

**Comment by MattUnderscoreZhang** [comment]
Tests and linting should pass now.

**Comment by MattUnderscoreZhang** [comment]
Where's your black configuration? Mine gives different results.

**Comment by iejMac** [comment]
nice thanks for this

**Pull request merged**
