### PR TITLE
SLURM improvments, audio fixes

### PR DESCRIPTION
**Pull request by m-bain**

### CODE REVIEW

**Comment by iejMac** [comment]
I need to fix tests, they are tweaking. LGTM, let me know if this is good to merge

**Comment by m-bain** [comment]
Just added some patch to get audio sub sampling (& converting format) working. Btw This repo so helpful for making video webdatasets thank you jeez

**Comment by iejMac** [comment]
glad its getting some use! if you could update the test_audio_subsampler unit test (update the call in there since you changed the func signature) we can merge this! thanks for contributing

**Comment by m-bain** [comment]
@iejMac ok updated the tests. 
Also added optional `TEST_ARGS` to the make test in case just wanting to run a specific subset of tests

**Comment by iejMac** [comment]
great! LGTM, thanks

**Pull request merged**
